<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BusaraUgs</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Busara.Domain\Busara.Domain.csproj" />
    <PackageReference Include="Com.Unity.Services.CloudCode.Core" Version="0.0.7" />
    <PackageReference Include="Com.Unity.Services.CloudCode.Apis" Version="0.0.27" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
  </ItemGroup>
</Project>
